version: '2'
services: 
#### DB zone ####
  db_service:
    image: mariadb:latest
    restart: always 
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes: 
      - ./db_service.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${CI_DB_PASS}
      MYSQL_USER: ${CI_DB_USER}
      MYSQL_PASSWORD: ${CI_DB_PASS}
#### PhpMyadmin ####
  phpmyadmin_service:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    links:
      - db_service
    environment:
      MYSQL_USERNAME: ${CI_DB_USER}
      MYSQL_ROOT_PASSWORD: ${CI_DB_PASS}
      PMA_HOST: ${CI_DB_HOST}